#!/bin/bash

# 🔍 Check GitHub Repository Permissions
echo "🔍 Checking Repository Permissions for GitHub Actions"
echo "===================================================="

echo ""
echo "📋 PERMISSIONS FIX APPLIED:"
echo "----------------------------"
echo "✅ Added permissions to workflow:"
echo "   - contents: write (push to repo)"
echo "   - pages: write (deploy to Pages)"  
echo "   - id-token: write (authentication)"
echo ""
echo "✅ Fixed git push command:"
echo "   - Changed from 'git push' to 'git push origin HEAD'"
echo "   - Added GITHUB_TOKEN environment variable"

echo ""
echo "🎯 NEXT STEPS TO VERIFY:"
echo "------------------------"
echo ""
echo "1️⃣ Check Repository Settings:"
echo "   URL: https://github.com/Liam-and-Son-Group/baoviet-danang/settings/actions"
echo "   Workflow permissions should be: 'Read and write permissions'"
echo ""
echo "2️⃣ Test Fixed Workflow:"
echo "   gh workflow run deploy-new-article.yml \\"
echo "     -f article_id=\"85bf05a9-edaa-40b3-96a6-12d27cff3c77\" \\"
echo "     -f article_filename=\"test-fix.html\""
echo ""
echo "3️⃣ If still fails, use Personal Access Token:"
echo "   - Create PAT: https://github.com/settings/tokens"
echo "   - Add to secrets as PERSONAL_ACCESS_TOKEN"
echo "   - Use workflow: deploy-with-pat.yml"

echo ""
echo "🚨 COMMON ISSUES & SOLUTIONS:"
echo "-----------------------------"
echo ""
echo "❌ Issue: Branch protection rules"
echo "✅ Solution: Check Settings → Branches, disable protection for Actions"
echo ""
echo "❌ Issue: Repository visibility (private repo)"
echo "✅ Solution: May need Personal Access Token for private repos"
echo ""
echo "❌ Issue: Organization permissions"
echo "✅ Solution: Organization may restrict Actions permissions"

echo ""
echo "📊 WORKFLOW STATUS:"
echo "------------------"
echo "Original workflow: deploy-new-article.yml (with permissions fix)"
echo "Backup workflow: deploy-with-pat.yml (uses Personal Access Token)"

echo ""
echo "🎯 EXPECTED RESULT AFTER FIX:"
echo "-----------------------------"
echo "✅ Checkout repository"
echo "✅ Generate article HTML"  
echo "✅ Update sitemap"
echo "✅ Commit & push changes ← Should work now!"
echo "✅ Deploy to GitHub Pages"

echo ""
echo "===================================================="
echo "🎉 Permissions fix applied! Test workflow now! 🚀"